name: ci

on:
  push:
    branches:
      - main
      - master
jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - name: 'Automated Version Bump'
        uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          minor-wording: 'add,Adds,new,minor'
          major-wording: 'MAJOR,cut-major,major'
          patch-wording:
            'patch,fixes,patch' # Providing patch-wording will override commits
            # defaulting to a patch bump.
          rc-wording: 'RELEASE,alpha'
